In [1]:
import tensorflow as tf

In [2]:
hello=tf.constant("Hello world",name='Hello')

In [5]:
sess=tf.Session()
print(sess.run(hello))

b'Hello world'


In [6]:
stk="Hi How are you?"

In [7]:
import numpy as np

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
type(np.array([0,2,3,5]))

numpy.ndarray

In [17]:
np.array([0,2,3,5]).shape
np.array([0,2,3,5]).reshape((4,1))

array([[0],
       [2],
       [3],
       [5]])

In [20]:
np.random.normal(2,0.1,10).reshape((5,2))

array([[ 1.92571879,  2.1086289 ],
       [ 2.17520443,  1.94543119],
       [ 1.77205038,  1.86491807],
       [ 2.02121014,  1.95314683],
       [ 1.95141294,  1.90280463]])

In [32]:
class Simpleclass():
    def __init__(self,name):
        print("hello "+name)
    def yell(self):
        print("Yelling")

In [7]:
fic=Simpleclass()

hello


In [8]:
fic.yell()

Yelling


In [34]:
class extendedclass(Simpleclass):
    def __init__(self):
        super().__init__('Jose')
        print("Extended")

In [24]:
fic1=Simpleclass('Jose')

hello Jose


In [25]:
fic1.yell()

Yelling


In [35]:
fic2=extendedclass()

hello Jose
Extended


In [36]:
fic2.yell()

Yelling
